language: python
python:
    - "3.5"
    - "3.6"


install:
    - sudo ./bootstrap-dev-debian.sh
    - ./bootstrap-dev-pip.sh system


script:
    - git fetch --unshallow
    - git fetch --all
    - git fetch --tags
    # users should be able to build without python dev dependencies
    - make
    # for dev
    - make dev
    # check
    - make check
    - make build
    - make test


deploy:
  provider: pypi
  user: stibbons
  skip_cleanup: true  # keep build artifacts for paths.py !
  distributions: sdist bdist_wheel
  password:
    secure: >
        MIbsyar7H1epBcp+TpSJ3APYUnIiQAB0M9cLEXFzqwJU1bjPev8fYNbfCQB0bA/TSHXaQjfR
        F3sTFFYxpVOxjRHPIWctBTTuKOETAd3XR96YtVRGLpglxLvI+9U5YPuGWC4SbKuAE8L8pqH9
        O9pnKqZCaarGxOm+GjEZrfzfm1g=
  on:
    tags: true
    repo: Guake/guake
    condition: $TRAVIS_PYTHON_VERSION = 3.6
